pipelines:
    default:
        - step:
            image: luminositylabs/maven:3.5.4-zulu8u181-8.31.0.1
            script:
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging dependency:list-repositories
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging dependency:tree
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging help:active-profiles clean install
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging,jee8 help:active-profiles clean install
        - step:
            image: luminositylabs/maven:3.5.4-zulu9u07-9.0.7.1
            script:
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging dependency:list-repositories
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging dependency:tree
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging help:active-profiles clean install
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging,jee8 help:active-profiles clean install
        - step:
            image: luminositylabs/maven:3.5.4-zulu10u02-10.3
            script:
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging dependency:list-repositories
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging dependency:tree
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging help:active-profiles clean install
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging,jee8 help:active-profiles clean install