image: maven:3.3.9-jdk-8

pipelines:
    default:
        - step:
            script:
                - mvn -U -V -Psonatype-snapshots,sonatype-staging dependency:list-repositories
                - mvn -U -V -Psonatype-snapshots,sonatype-staging dependency:tree
                - mvn -U -V -Psonatype-snapshots,sonatype-staging clean
                - mvn -U -V -Psonatype-snapshots,sonatype-staging install
